export const styles = theme => ({
    main: {
        width: 'auto',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        [theme.breakpoints.up(400 + theme.spacing(8))]: {
            width: 339,
        },
    },
    paper: {
        borderRadius: '7px',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        padding: "0 42px 27px 42px",
        width: "100%",
        position: 'relative',
        boxShadow: '0px 0px 10px 1px rgba(165, 175, 186, 0.16)',
    },
    avatar: {
        backgroundColor: "#E91D3D",
        width: "150px",
        height: "150px",
        position: 'absolute',
        top: 75,
    },
    submit: {
        marginTop: theme.spacing(3),
    },
    typographyTitle: {
        color: 'rgba(0, 0, 0, 1)',
        fontFamily: 'Avenir',
        fontSize: '22px',
        fontWeight: 'bold',
        fontStyle: 'normal',
        fontStretch: 'normal',
        lineHeight: 'normal',
        letterSpacing: 'normal',
        textAlign: 'center',
    },
    typographyTitleI: {
        marginTop: '5px',
        color: 'rgba(0, 0, 0, 0.9)',
        fontFamily: 'Avenir',
        fontSize: '18px',
        fontWeight: 'Book',
        fontStyle: 'normal',
        fontStretch: 'normal',
        lineHeight: 'normal',
        letterSpacing: 'normal',
        textAlign: 'center',
    },
    typographyText: {
        marginTop: '20px',
        color: 'rgba(72, 72, 72, 0.8)',
        fontFamily: 'Avenir',
        fontSize: '17px',
        fontWeight: 'Book',
        fontStyle: 'normal',
        fontStretch: 'normal',
        lineHeight: 'normal',
        letterSpacing: 'normal',
        textAlign: 'center',
        marginBottom: '30px'
    }
})